version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-major-versions:
        update-types:
        - "minor"
        - "patch"
