# This job exists to make sure it doesn't fail when built on Linux machines, it
# should just no-op
name: Go (Linux)
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
