name: Go (macOS)
on: [push]
jobs:

  build:
    name: Go ${{ matrix.go }} (CGO ${{ matrix.cgo == '1' && 'enabled' || 'disabled' }})
    runs-on: macos-latest
    env:
      GOTOOLCHAIN: local
      CGO_ENABLED: ${{ matrix.cgo }}
      TEST_KEYCHAIN: 1
      TEST_CTK_IDENTITY: 1
    strategy:
      matrix:
        go: [stable] #[ stable, oldstable ]
        cgo: ['0', '1']

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
